/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.v;

/**
 *
 * @author Nann
 */
public class displayApp extends javax.swing.JFrame {

    /**
     * Creates new form displayApp_profile
     */
    public displayApp() {
        initComponents();
        btnca.setToolTipText("create account");
        btntf2.setToolTipText("transfer");
        btnin.setToolTipText("interest");
        btndp.setToolTipText("deposit");
        btnwd.setToolTipText("withdraw");
        btnsm.setToolTipText("statement");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        btndp = new javax.swing.JButton();
        btnwd = new javax.swing.JButton();
        btntf2 = new javax.swing.JButton();
        btnca = new javax.swing.JButton();
        btnsm = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 450, 90, 40);

        btndp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/dep.gif"))); // NOI18N
        btndp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndpActionPerformed(evt);
            }
        });
        getContentPane().add(btndp);
        btndp.setBounds(350, 330, 92, 88);

        btnwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/wd.gif"))); // NOI18N
        btnwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwdActionPerformed(evt);
            }
        });
        getContentPane().add(btnwd);
        btnwd.setBounds(250, 330, 92, 88);

        btntf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/trans2.gif"))); // NOI18N
        btntf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntf2ActionPerformed(evt);
            }
        });
        getContentPane().add(btntf2);
        btntf2.setBounds(450, 330, 92, 88);

        btnca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/create.gif"))); // NOI18N
        btnca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaActionPerformed(evt);
            }
        });
        getContentPane().add(btnca);
        btnca.setBounds(350, 240, 92, 88);

        btnsm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/his.gif"))); // NOI18N
        btnsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsmActionPerformed(evt);
            }
        });
        getContentPane().add(btnsm);
        btnsm.setBounds(450, 240, 92, 88);

        btnin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/interest.gif"))); // NOI18N
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });
        getContentPane().add(btnin);
        btnin.setBounds(250, 240, 92, 88);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/v/banner1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 150);

        setSize(new java.awt.Dimension(800, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                emp_login emp = new emp_login();
                emp.setVisible(true);
                setVisible(false);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwdActionPerformed
        // TODO add your handling code here:
        withDrawal dp = new withDrawal();
        dp.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_btnwdActionPerformed

    private void btndpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndpActionPerformed
        // TODO add your handling code here:
        deposit wd = new deposit();
        wd.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btndpActionPerformed

    private void btntf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntf2ActionPerformed
        // TODO add your handling code here:
        transfer_not acc = new transfer_not();
        acc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btntf2ActionPerformed

    private void btncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaActionPerformed
        // TODO add your handling code here:
        create_account acc = new create_account();
        acc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncaActionPerformed

    private void btnsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsmActionPerformed
        // TODO add your handling code here:
        statement_printout print = new statement_printout();
        print.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnsmActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:
        interest in = new interest();
        in.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btninActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displayApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnca;
    private javax.swing.JButton btndp;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnsm;
    private javax.swing.JButton btntf2;
    private javax.swing.JButton btnwd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
